Fix compile failure due to null annotations on core platform
Change https://r.android.com/1667508 adds nullability annotations to
the core platform APIs which broke this code with the error:

cts/tests/tests/resourcesloader/src/android/content/res/loader/cts/ResourcesLoaderTestBase.kt:49:31: error: Java type mismatch expected (Mutable)Map<(raw) Any?, (raw) Any?>! but found ArrayMap<String, String>. Use explicit cast
            return JSONObject(ArrayMap<String, String>().apply { putAll(m) }).toString()

That appears to be because JSONObject takes a raw possibly mutable Map
and so Kotlin requires that it be passed a Map<Any?,Any?>. It is not
clear why this worked before. This change works with or without the
core platform API changes.

Bug: 183938110
Test: m checkbuild
Change-Id: I24a10940be8f3d912e66d74509b3d2da470ab6ff