Deflake AutoRevokeTest: run the job multiple times
Since b/155493913, the first run after boot is skipped if the process is
still running. Run the revoke again to be 100% sure that it happens
and the test gets to the next stage.

Symptom of the job not running properly after boot:

expected:<PERMISSION_[DENI]ED> but was:<PERMISSION_[GRANT]ED>
	at SystemUtil.eventually(SystemUtil.java:304)
	at SystemUtil.eventually(SystemUtil.java:279)
	at testUnusedApp_getsPermissionRevoked(AutoRevokeTest.kt:490)

Bug: 163432048
Change-Id: Ic9d2937f6e644d344fd230176938fbae89580f6e