Revert "[RenderScript] correctness test for L2 BLAS"
error: code too large, moving to native one

This reverts commit b653b6e778c56921a5b9dc1c6da8a1378f419100.

Change-Id: I9a2442d1f999340a5cb9cccd240f9131ea26213d