fix broken GPL build
cts/tests/tests/os/src/android/os/storage/cts/StorageManagerTest.java:171: error: cannot find symbol
        Assert.assertArrayEquals(expected, actual);
        ^
  symbol:   variable Assert
  location: class StorageManagerTest
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

(cherrypicked from commit 2d15f6aeeb9eb324cc2f34d5ca74c00797a9783b)

Change-Id: I541e5775e0e1c7efb22498d06a18f4401769b635