Introduce seapp_neverallow test
Augment existing seapp_contexts check to pass in the
general seapp_contexts neverallow file. Also, utilize
silent output feature of checkseapp.

Example Failure:
06-16 14:01:01 I/0a83bb8b: android.cts.security.SELinuxHostTest#testValidSeappContexts FAIL
junit.framework.AssertionFailedError: The seapp_contexts file was invalid:
Error: Rule in File "/tmp/seapp_contexts4625729967117239733.tmp" on line 10: "user=fake domain=system_app type=app_data_file" violates neverallow in File "/tmp/SELinuxHostTest8318648480567665560.tmp" on line 1: "user=((?!system).)* domain=system_app"

Change-Id: I171ed43cf4ae4961f66d5d8f56695345493f1261
Signed-off-by: William Roberts <william.c.roberts@intel.com>