Fix errorprone builds
I9a771809eb02a69fc89b212cd1292434af2d2b8b broke errorprone builds with:
cts/tests/tests/media/src/android/media/cts/NativeClearKeySystemTest.java:144: error: [MissingFail] Not calling fail() when expecting an exception masks bugs
testGetPropertyStringNative(uuidByteArray(COMMON_PSSH_SCHEME_UUID),
^
(see http://errorprone.info/bugpattern/MissingFail)
Did you mean '"unknown-property", value);'?

Add a fail if the unexpected exception is not thrown.

Bug: 64804932
Test: m -j RUN_ERROR_PRONE=true out/target/common/obj/APPS/CtsMediaTestCases_intermediates/classes-full-debug.jar
Change-Id: I88dfce568939e14631acced3bc52ac261c23b448